---
title: "R Package Development Log"
author: "Amali Jayatileke"
date: "2025-03-16"
output: html_document
---

# Development Log

## March 4-5
- **Tasks**: 
  - Explored the feasibility of sending automated news alerts using R's `blastula` package.
  - Excluded this feature from the project scope due to the requirement for extensive user-side configurations.
  - Proposed an alternative focus on Fake News analysis.
- **Purpose**: Defined the project scope by experimenting with different use cases.
- **GitHub Commit**: NA 


## March 10  
- **Tasks**: 
  - Developed functions for Clickbait Detection and Article Similarity Analysis using R's `tm` and `text2vec` packages for NLP (Natural Language Processing).
  - Setup access to OpenAI API to develop functions for Clickbait Detection and Article Similarity Analysis using Open AI LLM models.
  - Combined these functions into a unified methodology, `fake_news_detection()`.
- **Purpose**: Defined the project scope by experimenting with different use cases.
- **GitHub Commit**: [b9400f9](https://github.com/ajayatil/elmiguelon/commit/b9400f9e9aeb243e6ecf62c9646c9370ecc02d61)

## March 12  
- **Tasks**: 
  - Integrated `get_full_article()` into `fake_news_detection()`. Since NewsAPI provides only partial article content, this function performs web scraping to retrieve the full article for more accurate similarity analysis.
  - Added function documentation using `Roxygen`.
  - Created four unit tests for the function.
- **Purpose**: Improved similarity analysis accuracy and enhanced usability with documentation and unit testing.
- **GitHub Commit**: [3540f68](https://github.com/ajayatil/elmiguelon/commit/3540f681687ee3ebc74e3fca681f316c1903d99d)  

## March 13  
- **Tasks**: Refined `fake_news_detection()` and unit tests to ensure consistent outputs.
- **Purpose**: Strengthened package reliability through improved function structure and test coverage.
- **GitHub Commit**: [da17f52](https://github.com/ajayatil/elmiguelon/commit/da17f52b5c772d5bc21d0d4d2abdd496e36ecd34)  

## March 14  
- **Tasks**: Fixed bugs in `fake_news_detection()` and unit test scripts.Added CONTRIBUTING.md and Code of Conduct files to the repository. Began working on presentation slides.
- **Purpose**: Prepared the package for public use with proper documentation and debugging.  
- **GitHub Commit**: [d962804](https://github.com/ajayatil/elmiguelon/commit/d9628047c14a228322390cdce9c3fc6181a3a8f7)  

## March 15  
- **Tasks**: Updated README.md with examples and detailed explanations of the `fake_news_detection()` function.
Continued refining group presentation slides. 
- **Purpose**: Improved usability through clear documentation and practical examples.
- **GitHub Commit**: [5bb1da2](https://github.com/ajayatil/elmiguelon/commit/5bb1da2e2d1c2fd523450e319675cf70048a74a1)  


## March 16 
- **Tasks**: Implemented CI/CD integration using GitHub Actions, Refined `fake_news_detection()` function.
- **Purpose**: Automated testing and deployment to improve workflow efficiency.
- **GitHub Commit**: [db0eca4](https://github.com/ajayatil/elmiguelon/commit/db0eca4559fcf1e7d71c92f601d9506c25b00642)  

## March 17 
- **Tasks**: 
  - Expanded `vignette.Rmd` with additional details on `fake_news_detection()`.
  - Integrated CI/CD workflow using GitHub Actions. 
- **Purpose**: Enhanced documentation and automated testing for improved reliability.
- **GitHub Commit**: [f4feff4](https://github.com/ajayatil/elmiguelon/commit/f4feff4998fef4a29a7b96a6babab125a678e033)
