---
title: "R Package Development Log"
author: "Jenny Chung"
date: "2025-03-16"
output: html_document
---

# Development Log

## March 8  
- **Tasks**: Implemented core functions: `save_api_keys()`, `get_news_everything()`, and `get_top_headlines()`.  
- **Purpose**: set the foundation of the package by creating essential API interaction functions.  
- **GitHub Commit**: [d06bf9c](https://github.com/ajayatil/elmiguelon/commit/d06bf9ca14858e89f4f24774c41045aeca817dcf)  

## March 10  
- **Tasks**: Added `search_and_translate_article()` and `get_full_article()`.  
- **Purpose**: Extended functionality to support article translation and retrieval.  
- **GitHub Commit**: [5166df5](https://github.com/ajayatil/elmiguelon/commit/5166df5d794673fdc7665db132ff8ec5db6e6f79)  

## March 12  
- **Tasks**: Refactored and modularized all functions.  
- **Purpose**: Improved code maintainability and scalability.  
- **GitHub Commit**: [8ed07aa](https://github.com/ajayatil/elmiguelon/commit/8ed07aae72488263f4ecebced55fcfa44104714c)  

## March 13  
- **Tasks**: Updated unit tests and further modularized `get_full_article()`.  
- **Purpose**: Strengthened the reliability of the package by ensuring test coverage and better function structure.  
- **GitHub Commit**: [da17f52](https://github.com/ajayatil/elmiguelon/commit/da17f52b5c772d5bc21d0d4d2abdd496e36ecd34)  

## March 14  
- **Tasks**: 
  - Updated `README.md` file
  - Finalized package structure 
  - Fixed bugs to ensure proper functionality
- **Purpose**: Prepared the package for public use with proper documentation and debugging.  
- **GitHub Commit**: [89e7ab8](https://github.com/ajayatil/elmiguelon/commit/89e7ab8189bc0ca1e7050759efc2f16d36a8f6d0)  

## March 15  
- **Tasks**: 
  - Added examples for `get_top_headlines()`
  - Updated `README.md` and `vignette.Rmd` 
  - Built the vignette file.  
- **Purpose**: Enhanced usability with clear examples and documentation.  
- **GitHub Commit**: [e98df74](https://github.com/ajayatil/elmiguelon/commit/e98df744bdc4d892c21685d95bdc124e917d779c)

## March 17 
- **Tasks**: 
  - Added unit tests for `get_news_everything()` and `get_top_headlines()` functions
  - Updated the `vignette.Rmd` to include example results
  - Fixed minor bugs
- **Purpose**: Enhance functionality with improved testing, updated documentation, and bug fixes.  
- **GitHub Commit**: [867eaea](https://github.com/ajayatil/elmiguelon/commit/867eaea9417e1e9bfc4bf06c478cd0e2850f5771) 
